fixes:
  - "adiar/::" 

ignore:
  - "external"
  - "test"

coverage:
  precision: 3
  round: nearest
  range: "80...95"

  status:
    project:
      default:
        target: auto
        threshold: 1%
