var searchData=
[
  ['cases_0',['Nested Sweeping Cases',['../page__amend.html#autotoc_md41',1,'']]],
  ['changes_1',['Changes',['../page__amend.html#autotoc_md43',1,'']]],
  ['citing_20this_20project_2',['Citing this Project',['../page__cite.html',1,'page__papers']]],
  ['clear_3',['clear',['../classadiar_1_1builder.html#a76d693e760cee4e147cbdf1d68c211a9',1,'adiar::builder']]],
  ['cmake_4',['Building with CMake',['../page__getting_started.html#autotoc_md4',1,'']]],
  ['collapse_5fto_5fterminal_5',['collapse_to_terminal',['../structadiar_1_1statistics_1_1nested__sweeping__t_1_1outer__up__t.html#a8d27227da38ca7db0621c6fd99692680',1,'adiar::statistics::nested_sweeping_t::outer_up_t']]],
  ['combining_20bdds_6',['Combining BDDs',['../page__basic.html#autotoc_md9',1,'']]],
  ['constants_7',['constants',['../page__basic.html#autotoc_md17',1,'Boolean Constants'],['../page__basic.html#autotoc_md7',1,'Constants']]],
  ['constructing_20the_20board_8',['Constructing the Board',['../page__queens.html#autotoc_md32',1,'']]],
  ['construction_9',['Manual Construction',['../page__builder.html',1,'page__tutorial']]],
  ['constructors_10',['constructors',['../group__module____bdd____constructors.html',1,'Basic Constructors'],['../group__module____zdd____constructors.html',1,'Basic Constructors']]],
  ['consumer_11',['consumer',['../group__module____functional.html#ga3d65dbfd2713f575acf291dfbabd8e7b',1,'adiar']]],
  ['consumers_12',['consumers',['../page__functional.html#autotoc_md29',1,'Consumers'],['../page__functional.html#autotoc_md27',1,'Generators and Consumers']]],
  ['conversion_20to_20bdds_13',['Conversion to BDDs',['../group__module____bdd____conversion.html',1,'']]],
  ['conversion_20to_20zdds_14',['Conversion to ZDDs',['../group__module____zdd____conversion.html',1,'']]],
  ['cost_15',['cost',['../group__module____functional.html#ga3adf1876f8333cf8cbe78255823b0f8e',1,'adiar']]],
  ['count_16',['count',['../structadiar_1_1statistics.html#aef4c38a2f1741aeaa3ac55f8ef912be7',1,'adiar::statistics']]],
  ['count_5ft_17',['count_t',['../structadiar_1_1statistics_1_1count__t.html',1,'adiar::statistics']]],
  ['counting_20operations_18',['counting operations',['../group__module____zdd____counting.html',1,'Counting Operations'],['../page__basic.html#autotoc_md22',1,'Counting Operations'],['../group__module____bdd____counting.html',1,'Counting Operations']]],
  ['counting_20solutions_19',['Counting Solutions',['../page__queens.html#autotoc_md36',1,'']]],
  ['creating_20bdds_20',['Creating BDDs',['../page__basic.html#autotoc_md6',1,'']]],
  ['cubes_21',['Cubes',['../page__basic.html#autotoc_md19',1,'']]]
];
