name: cancel
on: [pull_request]

jobs:
  cancel:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        name: 'Benchmarks'
        with:
          workflow_id: 'benchmarks.yml'
          access_token: ${{ github.token }}
      - uses: styfle/cancel-workflow-action@0.9.0
        name: 'Examples'
        with:
          workflow_id: 'examples.yml'
          access_token: ${{ github.token }}
      - uses: styfle/cancel-workflow-action@0.9.0
        name: 'Unit tests'
        with:
          workflow_id: 'test.yml'
          access_token: ${{ github.token }}
