name: documentation

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  skip_duplicate:
    name: 'Skip job?'
    continue-on-error: true
    runs-on: ubuntu-latest

    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          paths: '["src/", "docs/"]'

    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}

  run_doxygen:
    name: 'Compile Doxygen'
    runs-on: ubuntu-latest

    needs: skip_duplicate
    if: ${{ needs.skip_duplicate.outputs.should_skip != 'true' }}

    steps:
    # Git repo set up
    - name: Checkout commit
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install C++ project dependencies
      run: sudo apt install libboost-all-dev

    - name: Install Doxygen and Graphviz
      run: sudo apt install doxygen graphviz

    # CMake build and create docs
    - name: CMake build
      working-directory: ${{github.workspace}}
      run: |
        cmake -E make_directory ${{github.workspace}}/build
        cd ${{github.workspace}}/build
        cmake ..

    - name: Make adiar_docs
      working-directory: ${{github.workspace}}/build
      run: make adiar_docs

    # Deploy on GitHub Pages if pushed to main
    - uses: JamesIves/github-pages-deploy-action@4.1.4
      if: ${{ github.event_name == 'push' }}
      with:
        branch: gh-pages
        folder: ${{github.workspace}}/build/docs/html/

  run_dummy:
    name: 'Compile Doxygen'
    runs-on: ubuntu-latest

    needs: skip_duplicate
    if: ${{ needs.skip_duplicate.outputs.should_skip == 'true' }}

    steps:
    - name: Echo skip
      run: |
        echo "Compiling documentation is skipped"
