name: static analysis

on: [pull_request]

jobs:
  include-guards:
    name: Check include guards
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Check include guard of adiar.h
      uses: sbeyer/include-guards-check-action@v1.0.0
      with:
        path: src/adiar
        pattern: '{file}'
        only: 'adiar\.h'

    - name: Check include guards of remaining files
      uses: sbeyer/include-guards-check-action@v1.0.0
      with:
        path: src/adiar
        pattern: 'ADIAR_{file}'
        ignore: 'adiar\.h'
