name: windows

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  skip_duplicate:
    name: 'Skip job?'
    continue-on-error: true
    runs-on: ubuntu-latest

    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          paths: '["src/", "test/"]'

    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}

  build_test:
    name: 'Build + Test (Windows)'
    runs-on: windows-latest

    needs: skip_duplicate
    if: ${{ needs.skip_duplicate.outputs.should_skip != 'true' }}

    strategy:
      fail-fast: false

    steps:
    # Git repo set up
    - name: Checkout commit
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    # Install dependencies
    - name: Set up Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.12.1
      with:
        arch: x64

    - name: Install Boost
      uses: MarkusJx/install-boost@v2.3.0
      id: install-boost
      with:
        # List of all versions here:
        # https://github.com/MarkusJx/prebuilt-boost/blob/main/versions-manifest.json
        boost_version: 1.79.0
        platform_version: 2019
        toolset: msvc

    - name: Install Graphviz
      uses: ts-graphviz/setup-graphviz@v1

    # Build
    - name: Build tests
      working-directory: ${{runner.workspace}}
      run: |
        cmake -E make_directory ${{github.workspace}}\build
        cd ${{github.workspace}}\build
        SET CXXFLAGS="%CXXFLAGS% -D_HAS_AUTO_PTR_ETC=1"
        cmake -D CMAKE_BUILD_TYPE=DEBUG -A x64 -T host=x64 -D ADIAR_STATS=ON -D Boost_INCLUDE_DIR=${{env.BOOST_ROOT}}\include -D Boost_LIBRARY_DIRS=${{env.BOOST_ROOT}}\lib ..
        cmake --build . --target test-adiar
      env:
        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}

    # Run unit tests
    - name: Run tests
      run: |
        & ${{github.workspace}}\build\test\Debug\test-adiar.exe --reporter=info --colorizer=light

